### ISSUE TITLE
A file non supported by Genio should be opened with the standard associated application

### ISSUE THREAD

**Issue by nexus6-haiku** [nexus6-haiku/Genio#15]
When a non supported file (e.g. an image) is double clicked in the project browser, it should be opened with the application associated with its mime type.

**Comment by Freaxed** [comment]
I did a commit on the project-folders branch so that in case of unsupported files, Genio starts the 'open' application to ask the Tracker to handle the file. I think this is better than searching for the default application inside genio and start it directly. The Tracker, in case of missing app, has already a clear workflow to interact with the user..

**Comment by nexus6-haiku** [comment]
Can we close this?

**Comment by Freaxed** [comment]
Yes!
